### PR TITLE
fix(git): add more robust error handling for Git operation

### LINKED ISSUE #571: Integration Modules (/action and /integrations): Add more robust error handling for Git operations
In `pull-request.ts`, Git operations are performed using `execSync` but could benefit from more detailed error handling and user-friendly error messages:

```

private createI18nBranch(i18nBranchName: string) {
 try {
   execSync(`git fetch origin ${this.platformKit.platformConfig.baseBranchName}`, { stdio: "inherit" });
   execSync(`git checkout -b ${i18nBranchName} origin/${this.platformKit.platformConfig.baseBranchName}`, {
     stdio: "inherit",
   });
 } catch (error) {
   this.ora.fail(`Failed to create branch: ${error.message}`);
   this.ora.info(`
     Troubleshooting tips:
     1. Make sure you have permission to create branches
     2. Check if the branch already exists locally (try 'git branch -a')
     3. Verify connectivity to remote repository
   `);
   throw new Error(`Branch creation failed: ${error.message}`);
 }
}
```

### PR DESCRIPTION
**Pull request by SXsid**
Resolves #571

### CODE REVIEW

**Comment by SXsid** [comment]
it has some changes of #573 but the bibucet gitconifg methos doesn't include the git command, which can be refactored

File: action/src/flows/pull-request.ts [hunk 1]
```diff
@@ -61,7 +61,7 @@ export class PullRequestFlow extends InBranchFlow {
   private async ensureFreshPr(i18nBranchName: string) {
     // Check if PR exists
     this.ora.start(
-      `Checking for existing PR with head ${i18nBranchName} and base ${this.platformKit.platformConfig.baseBranchName}`,
+      `Checking for existing PR with head ${i18nBranchName} and base ${this.platformKit.platformConfig.baseBranchName}`
```
Comment (mathio) [inline action/src/flows/pull-request.ts:64]: Thanks for running the prettier!

File: action/src/platforms/git-utils.ts
Comment (mathio) [inline action/src/platforms/git-utils.ts:1]: Let's not add a new utils file. Parent `PlatformKit` class has `gitConfig()` method that can be used for any common logic using `super.gitConfig(...)`

File: action/src/platforms/github.ts [hunk 2]
```diff
@@ -76,9 +77,9 @@ export class GitHubPlatformKit extends PlatformKit {
     if (ghToken && processOwnCommits) {
       console.log("Using provided GH_TOKEN. This will trigger your CI/CD pipeline to run again.");
 
-      execSync(`git remote set-url origin https://${ghToken}@github.com/${repositoryOwner}/${repositoryName}.git`, {
-        stdio: "inherit",
-      });
+      const URL = `https://${ghToken}@github.com/${repositoryOwner}/${repositoryName}.git`;
```
Comment (mathio) [inline action/src/platforms/github.ts]: Let's use lowercase "url" for variables like this:

```suggestion
      const url = `https://${ghToken}@github.com/${repositoryOwner}/${repositoryName}.git`;
```

**Review by mathio — CHANGES_REQUESTED** [review]

File: action/src/platforms/git-utils.ts
Comment (SXsid) [reply action/src/platforms/git-utils.ts:1]: Issue #573 mentioned creating a new file, so should I revert the multi-platform refactoring change?

Comment (mathio) [reply action/src/platforms/git-utils.ts:1]: I am not saying not to do it, just to do it a bit differently than what the issue suggests.

However lets keep the PRs one issue at a time. This looks good now.

**Review by mathio — APPROVED** [review]
